EHRWebApplication/Models/PatientViewModel.cs
using Model.DAO;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace EHRWebApplication.Models
{
    public class PatientViewModel
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Campo obrigatório.")]
        [Display(Name = "Nome")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Campo obrigatório.")]
        [Display(Name = "Sobrenome")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "Campo obrigatório.")]
        [Display(Name = "Data de nascimento")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime? Birth { get; set; }

        [Required(ErrorMessage = "Campo obrigatório.")]
        [Display(Name = "Sexo")]
        public short Sex { get; set; }

        public Dictionary<short, string> SexList
        {
            get { return SexDictionary.SexList; }
            set { }
        }

        public UserViewModel User { get; set; }
    }

    public class PatientDetailsViewModel
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Campo obrigatório.")]
        [Display(Name = "Nome")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Campo obrigatório.")]
        [Display(Name = "Sobrenome")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "Campo obrigatório.")]
        [Display(Name = "Data de nascimento")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime? Birth { get; set; }

        [Required(ErrorMessage = "Campo obrigatório.")]
        [Display(Name = "Sexo")]
        public string Sex { get; set; }

        [Required(ErrorMessage = "Campo obrigatório.")]
        [Display(Name = "EHR nº")]
        public string EhrNumber { get; set; }

        public User User { get; set; }
    }

    public class PatientEditViewModel
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Campo obrigatório.")]
        [Display(Name = "Nome")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Campo obrigatório.")]
        [Display(Name = "Sobrenome")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "Campo obrigatório.")]
        [Display(Name = "Data de nascimento")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime? Birth { get; set; }

        [Required(ErrorMessage = "Campo obrigatório.")]
        [Display(Name = "Sexo")]
        public short Sex { get; set; }

        public Dictionary<short, string> SexList
        {
            get { return SexDictionary.SexList; }
            set { }
        }

        public UserEditViewModel User { get; set; }
    }
}

EHRWebApplication/Controllers/PatientRecordsController.cs
using EHRWebApplication.Models;
using Model.BLL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EHRWebApplication.Controllers
{
   // [RoutePrefix("patient/{id:int}")]
    public class PatientRecordsController : MainController
    {
        // GET: PatientRecords
        [HttpGet]
       // [Route("consultas")]
        public ActionResult Index(int id)
        {
            if (id > 0)
            {
                var patientRecords = PatientRecordBLL.GetPatientRecordsByPatientId(id)
                                                     .Select(pr => new PatientRecordViewModel {
                                                         Id = pr.Id,
                                                         CreatedAt = pr.CreatedAt,
                                                         Doctor = pr.Doctor.FirstName + " " + pr.Doctor.LastName,
                                                         OptName = pr.OperationalsTemplate.Name
                                                     });
                return View(patientRecords);
            }

            return View(new PatientRecordViewModel());
        }

        // GET: PatientRecords/Details/5
      //  [Route("consultas/{recordId:int}")]
        public ActionResult Details(int id, int recordId)
        {
            ViewBag.recordId = recordId;
            ViewBag.id = id;

            var patientRecord = PatientRecordBLL.GetPatientRecord(recordId);

            PatientRecordDetailsViewModel patientRecordVM = new PatientRecordDetailsViewModel();

            patientRecordVM.Id = patientRecord.Id;
            patientRecordVM.PatientId = patientRecord.PatientId;
            patientRecordVM.CreatedAt = patientRecord.CreatedAt;
            patientRecordVM.OptName = patientRecord.OperationalsTemplate.Name;
            patientRecordVM.Doctor = patientRecord.Doctor.FirstName + " " + patientRecord.Doctor.LastName;
            patientRecordVM.Data = patientRecord.Data;
           
            return View(patientRecordVM);
        }

        
    }
}

EHRWebApplication/Controllers/PatientsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Model.DAO;
using EHRWebApplication.Models;
using Model.BLL;

namespace EHRWebApplication.Controllers
{
    [Authorize]
    public class PatientsController : MainController
    {
        private ClinicalEntities db = new ClinicalEntities();

        // GET: Patients
        [Utils.Administrador]
        public ActionResult Index()
        {
            var patients = PatientBLL.GetPatients()
                .Select(l => new PatientDetailsViewModel
                {
                    Id = l.Id,
                    FirstName = l.FirstName,
                    LastName = l.LastName,
                    Birth = l.Birth,
                    Sex = SexDictionary.getValue(l.sex),
                    EhrNumber = l.EHR.ToString()
                });

            return View(patients);
        }

        // GET: Patients/Details/5
        public ActionResult Details(int? id, bool profile = false)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Patient patient;

            if (profile)
            {
                patient = PatientBLL.GetPatientByUserId(id);
                ViewBag.Title = "Perfil";
                ViewBag.resource = "Dados do Usuário";
            }
            else
            {
                patient = PatientBLL.GetPatientById(id);
                ViewBag.Title = "Dados do Paciente";
                ViewBag.resource = "Detalhes";
            }
            
            if (patient == null)
            {
                return HttpNotFound();
            }

            PatientDetailsViewModel patientViewModel = new PatientDetailsViewModel();

            patientViewModel.Id = patient.Id;
            patientViewModel.FirstName = patient.FirstName;
            patientViewModel.LastName = patient.LastName;
            patientViewModel.Birth = patient.Birth;
            patientViewModel.Sex = SexDictionary.getValue(patient.sex);
            patientViewModel.EhrNumber = patient.EHR.ToString();
            patientViewModel.User = patient.User;

            return View(patientViewModel);
        }

        // GET: Patients/Create
        [Utils.Administrador]
        public ActionResult Create()
        {
            var patientVM = new PatientViewModel();
            patientVM.User = new UserViewModel();

            return View(patientVM);
        }

        // POST: Patients/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Utils.Administrador]
        public ActionResult Create(PatientViewModel pa, UserViewModel User)
        {
            if (ModelState.IsValid)
            {
                Patient patient = new Patient();

                patient.FirstName = pa.FirstName;
                patient.LastName = pa.LastName;
                patient.sex = pa.Sex;
                patient.Birth = (DateTime) pa.Birth;

                User user = new User();
                user.Email = User.Email;
                user.UserName = User.UserName;
                user.Password = User.Password;
                user.RoleGroupID = (short) Roles.PATIENT;
                user.Status = 1;

                bool create = PatientBLL.AddPatient(patient, user);

                if (create)
                {
                    return RedirectToAction("Index");
                }
            }

            return View(pa);
        }

        // GET: Patients/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Patient patient = PatientBLL.GetPatientById(id);

            if (patient == null)
            {
                return HttpNotFound();
            }

            var patientVM = new PatientEditViewModel();
            patientVM.Id = patient.Id;
            patientVM.FirstName = patient.FirstName;
            patientVM.LastName = patient.LastName;
            patientVM.Sex = patient.sex;
            patientVM.Birth = patient.Birth;

            var userVM = new UserEditViewModel();
            userVM.Id = patient.User.Id;
            userVM.UserName = patient.User.UserName;
            userVM.Password = patient.User.Password;
            userVM.Email = patient.User.Email;
            patientVM.User = userVM;

            ViewBag.sexSelected = new SelectList(SexDictionary.SexList, "Key", "Value", patientVM.Sex);
            
            return View(patientVM);
        }

        // POST: Patients/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(
          //  [Bind(Include = "Id,FirstName,LastName,Birth,sex,UserId,EHR, UserName, Email, Password")]
            PatientEditViewModel pa,
            UserEditViewModel User)
        {
            if (ModelState.IsValid)
            {
                pa.User = User;

                Patient patient = new Patient();

                patient.Id = pa.Id;
                patient.FirstName = pa.FirstName;
                patient.LastName = pa.LastName;
                patient.sex = pa.Sex;
                patient.Birth = (DateTime)pa.Birth;

                User user = new User();

                user.Id = User.Id;
                user.Email = User.Email;
                user.UserName = User.UserName;
                user.Password = User.Password;


                var updated = PatientBLL.UpdatePatient(patient, user);

                if (updated)
                {
                    return RedirectToAction("Details", new { id = patient.Id });
                }
            }

            ViewBag.sexSelected = new SelectList(SexDictionary.SexList, "Key", "Value", pa.Sex);
            return View(pa);
        }

        // GET: Patients/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Patient patient = db.Patients.Find(id);
            if (patient == null)
            {
                return HttpNotFound();
            }
            return View(patient);
        }

        // POST: Patients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var delete = PatientBLL.DeletePatient(id);

            if (delete)
            {
                return RedirectToAction("Index");
            }

            return View("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EHRWebApplication/Views/Patients/Create.cshtml
@model EHRWebApplication.Models.PatientViewModel

@{
    ViewBag.Title = "Cadastro de Pacientes";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Cadastrar Paciente</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Birth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Birth, new { htmlAttributes = new { @class = "form-control", id = "birth" } })
                @Html.ValidationMessageFor(model => model.Birth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sex, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Sex,
                new SelectList(Model.SexList, "Key", "Value"),
                "- Selecione -",
                new { @class = "form-control", id = "" })

                @Html.ValidationMessageFor(model => model.Sex, "", new { @class = "text-danger" })
            </div>
        </div>
       
        <div class="form-group">
            @Html.LabelFor(model => model.User.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.User.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.User.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.User.Email, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.User.Email, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.User.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.User.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.User.Password, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.User.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Cadastrar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar para a lista", "Index")
</div>

@section Scripts {
    <script>
        $(document).ready(function (){
            $("#birth").inputmask("mask", { "mask": "99/99/9999" });
        });
    </script>
}

EHRWebApplication/Views/Patients/Details.cshtml
@model EHRWebApplication.Models.PatientDetailsViewModel

<h2>@ViewBag.Title</h2>

<div>
    <h4>@ViewBag.resource</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Birth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Birth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sex)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sex)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EhrNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EhrNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.Email)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar dados", "Edit", new { id = Model.Id }) |

    @{
        var role = (int)Session["role"];

        if (role == 1)
        {
            @Html.ActionLink("Voltar para a lista", "Index")
        }
        else
        {
            @Html.ActionLink("Meus procedimentos", "Index", "PatientRecords", new { id = Model.Id }, null)
        }
    }
    
</p>

EHRWebApplication/Views/Patients/Edit.cshtml
@model EHRWebApplication.Models.PatientEditViewModel

@{
    ViewBag.Title = "Cadastro de Pacientes";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Edição de dados do paciente</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.User.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Birth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Birth, new { htmlAttributes = new { @class = "form-control", id = "birth" } })
                @Html.ValidationMessageFor(model => model.Birth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sex, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("sexSelected", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Sex, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.User.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.User.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.User.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.User.Email, new { @class = "col-md-2 control-label" })
            <div class="col-md-10" style="padding-top: 7px;">
                @Model.User.Email
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.User.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.User.Password, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.User.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Atualizar" class="btn btn-default" />
            </div>
        </div>
    </div>
}
@{
    var role = (int)Session["role"];

    if (role == 1)
    {
        <div>
            @Html.ActionLink("Voltar para a lista", "Index")
        </div>
    }
}

@section Scripts {
    <script>
        $(document).ready(function (){
            $("#birth").inputmask("mask", { "mask": "99/99/9999" });
        });
    </script>
}

EHRWebApplication/Views/Patients/Index.cshtml
@model IEnumerable<EHRWebApplication.Models.PatientDetailsViewModel>

@{
    ViewBag.Title = "Lista de Pacientes";
}

<h2>@ViewBag.Title</h2>

<p>
    @Html.ActionLink("Cadatrar novo paciente", "Create")
</p>
<table class="table table-striped table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Birth)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sex)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EhrNumber)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Birth)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Sex)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EhrNumber)
        </td>
        <td>
            @Html.ActionLink("Editar", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Detalhes", "Details", new { id=item.Id })
        </td>
    </tr>
}

</table>