EHRWebApplication/Controllers/DoctorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Model.DAO;
using EHRWebApplication.Models;
using Model.BLL;

namespace EHRWebApplication.Controllers
{
    [Utils.Administrador]
    public class DoctorsController : MainController
    {
        private ClinicalEntities db = new ClinicalEntities();

        // GET: Doctors
        public ActionResult Index()
        {
            var doctors = DoctorBLL.GetDoctors()
                .Select(d => new DoctorDetailsViewModel
                {
                    Id = d.Id,
                    FirstName = d.FirstName,
                    LastName = d.LastName,
                    Birth = d.Birth,
                    Sex = SexDictionary.getValue(d.Sex),
                    CRMNumber = d.MedicId.ToString()
                });

            return View(doctors);
        }

        // GET: Doctors/Details/5
        public ActionResult Details(int? id, bool profile = false)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Doctor doctor;

            if (profile)
            {
                doctor = DoctorBLL.GetDoctorByUserId(id);
            }
            else
            {
                doctor = DoctorBLL.GetDoctorById(id);
            }

            if (doctor == null)
            {
                return HttpNotFound();
            }

            DoctorDetailsViewModel doctorDetails = new DoctorDetailsViewModel();

            doctorDetails.Id = doctor.Id;
            doctorDetails.FirstName = doctor.FirstName;
            doctorDetails.LastName = doctor.LastName;
            doctorDetails.Birth = doctor.Birth;
            doctorDetails.Sex = SexDictionary.getValue(doctor.Sex);
            doctorDetails.CRMNumber = doctor.MedicId.ToString();
            doctorDetails.User = doctor.User;

            return View(doctorDetails);
        }

        // GET: Doctors/Create
        public ActionResult Create()
        {
            var doctorVM = new DoctorViewModel();
            doctorVM.User = new UserViewModel();
            return View(doctorVM);
        }

        // POST: Doctors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create( DoctorViewModel doctorVM, UserViewModel User)
        {
            if (ModelState.IsValid)
            {
                Doctor doctor = new Doctor();
                doctor.FirstName = doctorVM.FirstName;
                doctor.LastName = doctorVM.LastName;
                doctor.Birth = (DateTime)doctorVM.Birth;
                doctor.Sex = doctorVM.Sex;
                doctor.MedicId = doctorVM.MedicId;

                User user = new User();
                user.Email = User.Email;
                user.UserName = User.UserName;
                user.Password = User.Password;
                user.RoleGroupID = (short)Roles.DOCTOR;
                user.Status = 1;

                bool create = DoctorBLL.AddDoctor(doctor, user);

                return RedirectToAction("Index");
            }

            return View(doctorVM);
        }

        // GET: Doctors/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var doctor = DoctorBLL.GetDoctorById(id);
            
            if (doctor == null)
            {
                return HttpNotFound();
            }

            var doctorVM = new DoctorEditViewModel();
            doctorVM.Id = doctor.Id;
            doctorVM.FirstName = doctor.FirstName;
            doctorVM.LastName = doctor.LastName;
            doctorVM.Birth = doctor.Birth;
            doctorVM.Sex = doctor.Sex;
            doctorVM.MedicId = doctor.MedicId;

            var userVM = new UserEditViewModel();
            userVM.Id = doctor.User.Id;
            userVM.UserName = doctor.User.UserName;
            userVM.Password = doctor.User.Password;
            userVM.Email = doctor.User.Email;
            doctorVM.User = userVM;
            
            ViewBag.sexSelected = new SelectList(SexDictionary.SexList, "Key", "Value", doctor.Sex);
            
            return View(doctorVM);
        }

        // POST: Doctors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(DoctorEditViewModel doctorVM)
        {
            if (ModelState.IsValid)
            {
                Doctor doctor = new Doctor();

                doctor.Id = doctorVM.Id;
                doctor.FirstName = doctorVM.FirstName;
                doctor.LastName = doctorVM.LastName;
                doctor.Sex = doctorVM.Sex;
                doctor.Birth = (DateTime)doctorVM.Birth;
                doctor.MedicId = doctorVM.MedicId;

                User user = new User();

                user.Id = doctorVM.User.Id;
                user.Email = doctorVM.User.Email;
                user.UserName = doctorVM.User.UserName;
                user.Password = doctorVM.User.Password;


                var updated = DoctorBLL.UpdateDoctor(doctor, user);

                if (updated)
                {
                    return RedirectToAction("Index");
                }
            }

            ViewBag.UserId = new SelectList(db.Users, "Id", "UserName", doctorVM.User.Id);
            return View(doctorVM);
        }

        // GET: Doctors/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Doctor doctor = db.Doctors.Find(id);
            if (doctor == null)
            {
                return HttpNotFound();
            }
            return View(doctor);
        }

        // POST: Doctors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
           /* Doctor doctor = db.Doctors.Find(id);
            db.Doctors.Remove(doctor);
            db.SaveChanges(); */
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EHRWebApplication/Controllers/PatientsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Model.DAO;
using EHRWebApplication.Models;
using Model.BLL;

namespace EHRWebApplication.Controllers
{
    [Authorize]
    public class PatientsController : MainController
    {
        private ClinicalEntities db = new ClinicalEntities();

        // GET: Patients
        [Utils.Administrador]
        public ActionResult Index()
        {
            var patients = PatientBLL.GetPatients()
                .Select(l => new PatientDetailsViewModel
                {
                    Id = l.Id,
                    FirstName = l.FirstName,
                    LastName = l.LastName,
                    Birth = l.Birth,
                    Sex = SexDictionary.getValue(l.sex),
                    EhrNumber = l.EHR.ToString()
                });

            return View(patients);
        }

        // GET: Patients/Details/5
        public ActionResult Details(int? id, bool profile = false)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Patient patient;

            if (profile)
            {
                patient = PatientBLL.GetPatientByUserId(id);
                ViewBag.Title = "Perfil";
                ViewBag.resource = "Dados do Usuário";
            }
            else
            {
                patient = PatientBLL.GetPatientById(id);
                ViewBag.Title = "Dados do Paciente";
                ViewBag.resource = "Detalhes";
            }
            
            if (patient == null)
            {
                return HttpNotFound();
            }

            PatientDetailsViewModel patientViewModel = new PatientDetailsViewModel();

            patientViewModel.Id = patient.Id;
            patientViewModel.FirstName = patient.FirstName;
            patientViewModel.LastName = patient.LastName;
            patientViewModel.Birth = patient.Birth;
            patientViewModel.Sex = SexDictionary.getValue(patient.sex);
            patientViewModel.EhrNumber = patient.EHR.ToString();
            patientViewModel.User = patient.User;

            return View(patientViewModel);
        }

        // GET: Patients/Create
        [Utils.Administrador]
        public ActionResult Create()
        {
            var patientVM = new PatientViewModel();
            patientVM.User = new UserViewModel();

            return View(patientVM);
        }

        // POST: Patients/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Utils.Administrador]
        public ActionResult Create(PatientViewModel pa, UserViewModel User)
        {
            if (ModelState.IsValid)
            {
                Patient patient = new Patient();

                patient.FirstName = pa.FirstName;
                patient.LastName = pa.LastName;
                patient.sex = pa.Sex;
                patient.Birth = (DateTime) pa.Birth;

                User user = new User();
                user.Email = User.Email;
                user.UserName = User.UserName;
                user.Password = User.Password;
                user.RoleGroupID = (short) Roles.PATIENT;
                user.Status = 1;

                bool create = PatientBLL.AddPatient(patient, user);

                if (create)
                {
                    return RedirectToAction("Index");
                }
            }

            return View(pa);
        }

        // GET: Patients/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Patient patient = PatientBLL.GetPatientById(id);

            if (patient == null)
            {
                return HttpNotFound();
            }

            var patientVM = new PatientEditViewModel();
            patientVM.Id = patient.Id;
            patientVM.FirstName = patient.FirstName;
            patientVM.LastName = patient.LastName;
            patientVM.Sex = patient.sex;
            patientVM.Birth = patient.Birth;

            var userVM = new UserEditViewModel();
            userVM.Id = patient.User.Id;
            userVM.UserName = patient.User.UserName;
            userVM.Password = patient.User.Password;
            userVM.Email = patient.User.Email;
            patientVM.User = userVM;

            ViewBag.sexSelected = new SelectList(SexDictionary.SexList, "Key", "Value", patientVM.Sex);
            
            return View(patientVM);
        }

        // POST: Patients/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(
          //  [Bind(Include = "Id,FirstName,LastName,Birth,sex,UserId,EHR, UserName, Email, Password")]
            PatientEditViewModel pa,
            UserEditViewModel User)
        {
            if (ModelState.IsValid)
            {
                pa.User = User;

                Patient patient = new Patient();

                patient.Id = pa.Id;
                patient.FirstName = pa.FirstName;
                patient.LastName = pa.LastName;
                patient.sex = pa.Sex;
                patient.Birth = (DateTime)pa.Birth;

                User user = new User();

                user.Id = User.Id;
                user.Email = User.Email;
                user.UserName = User.UserName;
                user.Password = User.Password;


                var updated = PatientBLL.UpdatePatient(patient, user);

                if (updated)
                {
                    return RedirectToAction("Details", new { id = patient.Id });
                }
            }

            ViewBag.sexSelected = new SelectList(SexDictionary.SexList, "Key", "Value", pa.Sex);
            return View(pa);
        }

        // GET: Patients/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Patient patient = db.Patients.Find(id);
            if (patient == null)
            {
                return HttpNotFound();
            }
            return View(patient);
        }

        // POST: Patients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var delete = PatientBLL.DeletePatient(id);

            if (delete)
            {
                return RedirectToAction("Index");
            }

            return View("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EHRWebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - EHRClinical</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("EHRClinical", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                @if (Session["auth"] != null)
                {
                    @Html.Action("_MenuPartial");
                }
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Aplicação desenvolvida utilizando o padrão OpenEHR</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/inputmask")
    @RenderSection("scripts", required: false)
</body>
</html>

EHRWebApplication/Views/Shared/_MenuPartial.cshtml
@model  IEnumerable<Model.DAO.Feature>

<ul class="nav navbar-nav">
    @foreach (var item in Model)
    {
        <li>
            @if (item.OperationalsTemplate.IsController == 1)
            {
                if (item.OperationalsTemplate.Template == "PatientRecords")
                {
                    @Html.ActionLink(item.Name, "Index", item.OperationalsTemplate.Template, new { id = ViewBag.Patient }, null);
                }
                else
                {
                    @Html.ActionLink(item.Name, "Index", item.OperationalsTemplate.Template);    
                }

            }
            else
            {
                <a href="#">@item.Name</a>    
            }
        </li>
    }
</ul>


@*<ul class="nav navbar-nav">
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Pacientes <span class="caret"></span></a>
            <ul class="dropdown-menu">
                <li>@Html.ActionLink("Cadastrar", "Create", "Patients")</li>

                    <li><a href="#">Another action</a></li>
                    <li><a href="#">Something else here</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="#">Separated link</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="#">One more separated link</a></li>

            </ul>
        </li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Médico <span class="caret"></span></a>
            <ul class="dropdown-menu">
                <li>@Html.ActionLink("Cadastrar", "Create", "Doctors")</li>

                    <li><a href="#">Another action</a></li>
                    <li><a href="#">Something else here</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="#">Separated link</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="#">One more separated link</a></li>

            </ul>
        </li>
    </ul>*@